modLoader="lowcodefml"
loaderVersion="*"
license="MIT"
[[mods]]
    modId="tinkers_hoes"
    version="1.0.0"
    displayName="Tinkers' Hoes"
    authors="OOrreeooss"
    description='''A Thing Pack for Tinkers' Construct that adds hoes.'''
[[dependencies.tinkers_hoes]]
    modId="tconstruct"
    mandatory=true
    versionRange="[3.10.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tinkers_hoes]]
    modId="jsonthings"
    mandatory=true
    versionRange="[0.9.9,)"
    ordering="NONE"
    side="BOTH"
